# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Mocha CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Git and clone calvin-network-data
      run: |
        sudo apt-get install git
        git clone https://github.com/ucd-cws/calvin-network-data
    - name: Run install for current package
      run: npm link -g calvin-network-tools
    - name: Install mocha testing framework
      run: npm install -g mocha 
    - run: npm run build --if-present
    - name: Run mocha tests
      run: mocha tests --recursive
